### PR TITLE
Add credentials and token flags to all sub commands

### PR DESCRIPTION
**Pull request by zamai**
Hi, nice project, I used it to upload videos via bash script.

I noticed that credentials and token flags where only working inside the Auth command, and rest of the sub commands relied on the hardcoded path of the client_secret.json - which is same folder as binary execution. Which does not really work for me, so I added these flags to all subcommands (not sure if it's the correct implementation, first coding with cobra).

Not sure if you want to merge this PR as is, or just take it's implementation as starting point for next version, just thought it might be worth sharing my patch.

🙏

### CODE REVIEW

**Comment by OpenWaygate** [comment]
Hi @zamai, nice catch about the document!
About these two new flags, I prefer using environment variables to modify the default value, so for these two functions:

https://github.com/eat-pray-ai/yutu/blob/b1cc0b1ee226c6ebd96114287680b5bfccb6ea4e/pkg/auth/auth.go#L216-L226

We can set values like this

```go
func WithCredential(cred string) Option {
	return func() {
		if cred != "" {
			credential = cred
			return
		}
		if cred, ok := os.LookupEnv("YUTU_CREDENTIAL"); ok {
			credential = cred
		}
	}
}

func WithCacheToken(token string) Option {
	return func() {
		// parameter > environment variable > default value
		if token != "" {
			cacheToken = token
			return
		}
		if token, ok := os.LookupEnv("YUTU_CACHE_TOKEN"); ok {
			cacheToken = token
		}
	}
}
```

Then when running a command with `nil` service

https://github.com/eat-pray-ai/yutu/blob/b1cc0b1ee226c6ebd96114287680b5bfccb6ea4e/pkg/activity/activity.go#L146-L154

we can pass the empty credential path and cacheToken path

```go
func WithService(svc *youtube.Service) Option {
	return func(a *activity) {
		if svc != nil {
			service = svc
		} else {
			service = auth.NewY2BService(
				auth.WithCredential(""),
				auth.WithCacheToken(""),
			)
		}
	}
}
```

**Comment by zamai** [comment]
Sure, your project your design :) 

I've already implemented flags in my fork - since that what I need in my environment. feel free to only cherrypick the  docs commit.

**Comment by OpenWaygate** [comment]
OK, I have cherry-picked your commit. Thanks again!

**Comment by OpenWaygate** [comment]
I have updated to use environment variables, so close this pr.

**Pull request closed without merging**
